/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as WarRoomRouteImport } from './routes/war-room'
import { Route as OIdRouteImport } from './routes/o/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const WarRoomRoute = WarRoomRouteImport.update({
  id: '/war-room',
  path: '/war-room',
  getParentRoute: () => rootRouteImport,
} as any)
const OIdRoute = OIdRouteImport.update({
  id: '/o/$id',
  path: '/o/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/radar': typeof RadarRoute
  '/stats': typeof StatsRoute
  '/updates': typeof UpdatesRoute
  '/war-room': typeof WarRoomRoute
  '/o/$id': typeof OIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/radar': typeof RadarRoute
  '/stats': typeof StatsRoute
  '/updates': typeof UpdatesRoute
  '/war-room': typeof WarRoomRoute
  '/o/$id': typeof OIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/radar': typeof RadarRoute
  '/stats': typeof StatsRoute
  '/updates': typeof UpdatesRoute
  '/war-room': typeof WarRoomRoute
  '/o/$id': typeof OIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/radar' | '/stats' | '/updates' | '/war-room' | '/o/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/radar' | '/stats' | '/updates' | '/war-room' | '/o/$id'
  id:
    '__root__' | '/' | '/radar' | '/stats' | '/updates' | '/war-room' | '/o/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RadarRoute: typeof RadarRoute
  StatsRoute: typeof StatsRoute
  UpdatesRoute: typeof UpdatesRoute
  WarRoomRoute: typeof WarRoomRoute
  OIdRoute: typeof OIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/war-room': {
      id: '/war-room'
      path: '/war-room'
      fullPath: '/war-room'
      preLoaderRoute: typeof WarRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$id': {
      id: '/o/$id'
      path: '/o/$id'
      fullPath: '/o/$id'
      preLoaderRoute: typeof OIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RadarRoute: RadarRoute,
  StatsRoute: StatsRoute,
  UpdatesRoute: UpdatesRoute,
  WarRoomRoute: WarRoomRoute,
  OIdRoute: OIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
